/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account (public self-serve)
         * @description Register a new user and create their first workspace. Returns
         *     onboarding metadata only — NO tokens. The client must call
         *     `/api/v2/auth/signin` separately to obtain an access token.
         *     Aligned with the Python dashboard's `/api/v2/auth/register`
         *     contract via #350.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deprecated alias for /api/v2/auth/register
         * @deprecated
         * @description Kept for backward compatibility. New clients MUST use `/register`.
         *     Returns the same RegisterResponse body — no tokens.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in to existing account */
        post: operations["signin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Rotate refresh token and get new access token
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify JWT access token */
        post: operations["verifyToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and revoke refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Response from `/api/v2/auth/register` (and its `/signup` alias).
         *     Per #350, register does NOT return tokens; the client must call
         *     `/signin` after register to obtain a session.
         */
        RegisterResponse: {
            /**
             * @description Always "ok" on a 201
             * @enum {string}
             */
            status: "ok";
            /**
             * Format: int64
             * @description ID of the newly created user
             * @example 42
             */
            user_id: number;
            /**
             * Format: int64
             * @description ID of the workspace created for this user
             * @example 17
             */
            workspace_id: number;
            /**
             * @description Role granted to the registering user in the new workspace
             * @enum {string}
             */
            role: "owner";
            /**
             * @description Whether the client should route to the onboarding flow
             * @example true
             */
            onboarding_required: boolean;
        };
        SignInResponse: {
            access_token: string;
            refresh_token: string;
            /** @example 3600 */
            expires_in: number;
            user: components["schemas"]["UserResponse"];
        };
        RefreshTokenResponse: {
            access_token: string;
            /** @description New refresh token (old one is rotated) */
            refresh_token: string;
            /** @example 3600 */
            expires_in: number;
        };
        VerifyTokenResponse: {
            valid: boolean;
            /** @description Stringified i64 user ID */
            user_id?: string | null;
            /**
             * Format: int64
             * @description Workspace ID
             */
            wid?: number | null;
            email?: string | null;
            /** @description Workspace-scoped role */
            role?: string | null;
            /** @description Platform-level role */
            global_role?: string | null;
        };
        UserResponse: {
            /**
             * Format: int64
             * @example 123
             */
            id: number;
            /** Format: email */
            email: string;
            display_name?: string | null;
            /** Format: int64 */
            active_workspace_id?: number | null;
            /**
             * @description Global role (superadmin|user)
             * @example user
             */
            role: string;
        };
        WorkspaceResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description URL-friendly identifier */
            slug: string;
            /** Format: int64 */
            owner_user_id: number;
        };
        CurrentUserResponse: {
            user: components["schemas"]["UserInfo"];
            workspace: components["schemas"]["WorkspaceInfo"];
        };
        UserInfo: {
            /** Format: int64 */
            id: number;
            email: string;
            display_name?: string | null;
            /** @description Workspace-scoped role */
            role: string;
            /** @description Platform-level role */
            global_role: string;
        };
        WorkspaceInfo: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        Error: {
            error?: string;
            message?: string;
            code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example securepassword123
                     */
                    password: string;
                    /** @example John Doe */
                    display_name?: string | null;
                    /** @example My Workspace */
                    workspace_name: string;
                };
            };
        };
        responses: {
            /** @description User + workspace created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                    display_name?: string | null;
                    workspace_name: string;
                };
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    signin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                    /** Format: int64 */
                    workspace_id?: number | null;
                };
            };
        };
        responses: {
            /** @description Sign in successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Opaque refresh token from sign-in/sign-up */
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verifyToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description JWT access token */
                    token: string;
                };
            };
        };
        responses: {
            /** @description Token verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
