# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-08-01T07:51:03+00:00

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class User(BaseModel):
    id: UUID
    email: EmailStr
    full_name: str = Field(..., max_length=255, min_length=1)
    avatar_url: AnyUrl
    roles: list[str]
    created_at: AwareDatetime


class Workspace(BaseModel):
    id: UUID
    name: str = Field(..., max_length=255, min_length=1)
    owner_id: UUID
    created_at: AwareDatetime


class Status(StrEnum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    paused = "paused"
    stopped = "stopped"


class Config(BaseModel):
    num_videos: int = Field(..., ge=1, le=100)
    niche: str = Field(..., max_length=255, min_length=1)
    auto_publish: bool | None = False
    parameters: dict[str, str] | None = None


class Progress(BaseModel):
    total_videos: int = Field(..., ge=0)
    completed_videos: int = Field(..., ge=0)
    failed_videos: int = Field(..., ge=0)
    current_stage: str
    progress_percent: float = Field(..., ge=0.0, le=100.0)
    started_at: AwareDatetime
    estimated_completion: AwareDatetime


class Job(BaseModel):
    id: UUID
    workspace_id: UUID
    channel_id: UUID
    status: Status
    config: Config
    progress: Progress
    created_at: AwareDatetime
    updated_at: AwareDatetime
    completed_at: AwareDatetime
    error_message: str


class JobConfig(BaseModel):
    num_videos: int = Field(..., ge=1, le=100)
    niche: str = Field(..., max_length=255, min_length=1)
    auto_publish: bool | None = False
    parameters: dict[str, str] | None = None


class JobProgress(BaseModel):
    total_videos: int = Field(..., ge=0)
    completed_videos: int = Field(..., ge=0)
    failed_videos: int = Field(..., ge=0)
    current_stage: str
    progress_percent: float = Field(..., ge=0.0, le=100.0)
    started_at: AwareDatetime
    estimated_completion: AwareDatetime


class JobProgressEvent(BaseModel):
    job_id: UUID
    status: Status
    progress: Progress
    stage: str
    message: str
    timestamp: AwareDatetime


class Principal(BaseModel):
    user_id: UUID
    workspace_id: UUID
    email: EmailStr
    roles: list[str]
    global_roles: list[str]
    permissions: list[str]


class PaginationRequest(BaseModel):
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(20, ge=1, le=100)
    cursor: str | None = None


class PaginationResponse(BaseModel):
    total: int = Field(..., ge=0)
    page: int = Field(..., ge=1)
    page_size: int = Field(..., ge=1)
    next_cursor: str
    has_more: bool


class ErrorDetail(BaseModel):
    code: str
    message: str
    metadata: dict[str, str] | None = None


class JobStatus(StrEnum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    paused = "paused"
    stopped = "stopped"


class TimeRange(BaseModel):
    start: AwareDatetime
    end: AwareDatetime


class ResourceMetadata(BaseModel):
    id: UUID
    created_at: AwareDatetime
    updated_at: AwareDatetime
    created_by: UUID
    updated_by: UUID
    version: int = Field(..., ge=0)
